Building DAG of jobs...
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	21	cluster_ecn_barcodes
	21	extract_barcodes_from_fq
	43

rule extract_barcodes_from_fq:
    input: /shared/gcf/l.dauban/6578/fastq_files/6578_21_pMT09_r1_r2_TGTACT_S21_R1_001.fastq.gz
    output: results_12/6578_21_pMT09_r1_r2_TGTACT_S21_barcodes.tsv
    log: logs/6578_21_pMT09_r1_r2_TGTACT_S21_extract_barcodes_from_fq.log
    jobid: 41
    wildcards: ecn=6578_21_pMT09_r1_r2_TGTACT_S21

Terminating processes on user request.
Error in rule extract_barcodes_from_fq:
    jobid: 41
    output: results_12/6578_21_pMT09_r1_r2_TGTACT_S21_barcodes.tsv
    log: logs/6578_21_pMT09_r1_r2_TGTACT_S21_extract_barcodes_from_fq.log

RuleException:
CalledProcessError in line 30 of /DATA/usr/m.trauernicht/projects/SuRE-TF/gen-2_mES/raw-data-analysis/Snakefile_12:
Command ' set -euo pipefail;  /DATA/usr/m.trauernicht/software/miniconda3/envs/tf-activity/bin/python /DATA/usr/m.trauernicht/projects/SuRE-TF/gen-2_mES/raw-data-analysis/.snakemake.hkgx9cxt.mt20201117_bc-counts.py ' returned non-zero exit status 1.
  File "/DATA/usr/m.trauernicht/projects/SuRE-TF/gen-2_mES/raw-data-analysis/Snakefile_12", line 30, in __rule_extract_barcodes_from_fq
  File "/DATA/usr/m.trauernicht/software/miniconda3/envs/tf-activity/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job extract_barcodes_from_fq since they might be corrupted:
results_12/6578_21_pMT09_r1_r2_TGTACT_S21_barcodes.tsv
Complete log: /DATA/usr/m.trauernicht/projects/SuRE-TF/gen-2_mES/raw-data-analysis/.snakemake/log/2021-09-30T145841.157715.snakemake.log
