Building DAG of jobs...
Provided cores: 6
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	cluster_ecn_barcodes
	1	extract_barcodes_from_fq
	3

rule extract_barcodes_from_fq:
    input: /DATA/usr/m.trauernicht/projects/SuRE-TF/data/gcf6371_K562/raw/6371_2_SuRE_cDNA_pMT02_BR1_CGATGT_S20_R1_001.fastq.gz
    output: results/6371_2_SuRE_cDNA_pMT02_BR1_CGATGT_S20_barcodes.tsv
    log: logs/6371_2_SuRE_cDNA_pMT02_BR1_CGATGT_S20_extract_barcodes_from_fq.log
    jobid: 2
    wildcards: ecn=6371_2_SuRE_cDNA_pMT02_BR1_CGATGT_S20

Terminating processes on user request.
Error in rule extract_barcodes_from_fq:
    jobid: 2
    output: results/6371_2_SuRE_cDNA_pMT02_BR1_CGATGT_S20_barcodes.tsv
    log: logs/6371_2_SuRE_cDNA_pMT02_BR1_CGATGT_S20_extract_barcodes_from_fq.log

RuleException:
CalledProcessError in line 30 of /DATA/usr/m.trauernicht/projects/SuRE-TF/gen-1_K562/raw-data-analysis/Snakefile:
Command ' set -euo pipefail;  /DATA/usr/m.trauernicht/software/miniconda3/envs/tf-activity/bin/python /DATA/usr/m.trauernicht/projects/SuRE-TF/gen-1_K562/raw-data-analysis/.snakemake.m5vjvjh9.mt20201117_bc-counts.py ' returned non-zero exit status 1.
  File "/DATA/usr/m.trauernicht/projects/SuRE-TF/gen-1_K562/raw-data-analysis/Snakefile", line 30, in __rule_extract_barcodes_from_fq
  File "/DATA/usr/m.trauernicht/software/miniconda3/envs/tf-activity/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job extract_barcodes_from_fq since they might be corrupted:
results/6371_2_SuRE_cDNA_pMT02_BR1_CGATGT_S20_barcodes.tsv
Complete log: /DATA/usr/m.trauernicht/projects/SuRE-TF/gen-1_K562/raw-data-analysis/.snakemake/log/2021-03-12T092011.364240.snakemake.log
